
name: Pytests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust to your Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy==1.23.0 torch numba opt_einsum # Add other dependencies here if needed
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run tests
    - name: Run pytest
      run: pytest tests/  # Adjust the path if your tests are in a different folder
